apiVersion: apps/v1
kind: Deployment
metadata:
  name: $CI_PROJECT_NAME-$CI_COMMIT_BRANCH
  namespace: $KUBE_NAMESPACE
  annotations:
    app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
    app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $CI_PROJECT_NAME-$CI_COMMIT_BRANCH
  template:
    metadata:
      labels:
        app: $CI_PROJECT_NAME-$CI_COMMIT_BRANCH
      annotations:
        app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
        app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
    spec:
      nodeSelector:
        hasGPU: "yes"
      hostname: $CI_PROJECT_NAME-$CI_COMMIT_BRANCH-1
      subdomain: $CI_PROJECT_NAME-$CI_COMMIT_BRANCH-subdomain
      imagePullSecrets:
        - name: regcred-registrycreds
      containers:
      - name: $CI_PROJECT_NAME-$CI_COMMIT_BRANCH
        image: 192.168.18.24:444/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: config-$CI_COMMIT_REF_NAME
        ports:
        - containerPort: ${FACECUP_PORT}
---
apiVersion: v1
kind: Service
metadata:
  name: $CI_PROJECT_NAME-$CI_COMMIT_BRANCH-subdomain
  namespace: $KUBE_NAMESPACE
spec:
  type: NodePort
  selector:
    app: $CI_PROJECT_NAME-$CI_COMMIT_BRANCH
  ports:
  - port: ${FACECUP_PORT}
    targetPort: ${FACECUP_PORT}
    nodePort: $NODE_PORT
