# Generated by Django 3.2.3 on 2021-07-31 12:03

import common.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='media/Rules')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='media\\logo')),
                ('kind', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Sponsor',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$')])),
                ('fa_name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[\u0600-ۿ\\s]+$')])),
                ('phone', models.CharField(max_length=11, null=True, unique=True, validators=[common.validators.mobile_validator, common.validators.mobile_length_validator])),
                ('code', models.FileField(null=True, upload_to='files/resume/codes')),
                ('verify_phone', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Team',
            },
        ),
        migrations.CreateModel(
            name='TeamUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[\u0600-ۿ\\s]+$')])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[\u0600-ۿ\\s]+$')])),
                ('file_resume', models.FileField(upload_to='files/resume/team_user')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mteam', to='team.team')),
            ],
            options={
                'db_table': 'TeamUser',
                'unique_together': {('team', 'first_name', 'last_name')},
            },
        ),
    ]
